### ISSUE TITLE
Not easy to debug error only in dev mode

### ISSUE THREAD

**Issue by emersonbottero** [vuejs/vitepress#1395]
### Describe the bug

The build and serve commands works but the dev doesn't.

 

### Reproduction

clone the [repo](https://github.com/emersonbottero/mermaid) 
- yarn build (you will get some post build error because I'm transitioning the documentation to vitepress)
- yarn vdocs:build
- yarn vdocs:serve (it works normally)
- yarn vdocs:dev (it will thrown an error)

The error thrown is misleading in my opinion..

Uncaught TypeError: Cannot read properties of undefined (reading 'accept')
    at VPSkipLink.vue:37:3
    
 

### Expected behavior

the error should point to the correct file?
I'm sure is not a problem in VPSkipLink file.
Is hard to debug without knowledge of vitepress internal logic  

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 8.47 GB / 15.92 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 105.0.5195.127
    Edge: Spartan (44.22621.601.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.15 => 1.0.0-alpha.15
```

### Additional context

I'm convincing the mermaidjs team to update their documentation to use vitepress 😁.
I created a repo from scratch first and it works without problem but in the mermaid repo this error may be a combination of the setting done in packaeg.json and tsconfig but! 

I think we really want anyone to be able to use vitepress to update any library out there (mission inspiration?? 😅) 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Finally got a reproduction 😅. (This is same as #1374 BTW. )

**Comment by brc-dd** [comment]
Fixed in https://github.com/vitejs/vite/pull/10207

**Comment by emersonbottero** [comment]
> Finally got a reproduction 😅. (This is same as #1374 BTW. )

why then I couldn't find it?
![image](https://user-images.githubusercontent.com/12377432/192111710-51712a80-fe13-4e82-8cd1-a4f6086f5639.png)

**Comment by yaman3bd** [comment]
@brc-dd  I am still having the same error,
 my file structure:
![Screen Shot 2022-09-24 at 10 54 23 PM](https://user-images.githubusercontent.com/58285821/192116118-1f7a9973-a6b3-4730-afbf-0435ac5fc992.png)

`config.ts` is empty,
`index.md` has just a demo message: # Hello world
I think by default it should show whatever inside `index.md` file
but after starting the server an empty page shows with the same error:
![Screen Shot 2022-09-24 at 10 57 12 PM](https://user-images.githubusercontent.com/58285821/192116207-14945d42-9ff6-488e-bd4e-62910f108762.png)
my packages versions:
```json
    "vite": "^3.1.2",
    "vitepress": "^1.0.0-alpha.16",
    "vue": "^3.2.39"
```
is there something missing, or wrong I am doing?

**Comment by emersonbottero** [comment]
@yaman3bd it as not been published yet.. 
wait for the next vite release!

**Comment by emersonbottero** [comment]
@brc-dd I'm still getting the same error.
You can update vitepress and vite in the mentioned repo to see the problem.

**Comment by brc-dd** [comment]
I haven't released a new version yet.

**Comment by brc-dd** [comment]
Weird, not working on alpha-18 too :/

**Comment by brc-dd** [comment]
Ah, this will be fixed in next version of @vitejs/plugin-vue
