### ISSUE TITLE
Unique names for files in /assets

### ISSUE THREAD

**Issue by tk1** [vuejs/vitepress#386]
### Is your feature request related to a problem? Please describe.

I  use vitepress to generate documentation for a GitHub project. The documentation will be generated locally and then pushed to GitHub. It is then deployed from the /docs folder to GitHub pages.

Every time I build the documentation the filenames in /assets will change. A filename looks for e.g. "index.md.497bee00.js". The part "497bee00" changes every time I build the documentation. As I must check it in in order to havbe the built documentation in my GitHub project, there are new filenames for each build. 

### Describe the solution you'd like

Use filenames in /asset, that are not changing for each build.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yyx990803** [comment]
Should be fixed by 929bcf5 (out in 0.18.1)

**Comment by tk1** [comment]
Unfortunately, this is not fixed. I should clarify the solution I'd like: There should be the possibility to have non-hashed filenames in .vitepress/dist/assets. Otherwise I have to check in the new files (and remove the old files) to GitHub every time the documentation has changed. This is because the built assets have to be under my project's  /docs folder because from there they are deployed to GitHub pages.
