### ISSUE TITLE
Outline marker does not move on click in certain cases

### ISSUE THREAD

**Issue by zqianem** [vuejs/vitepress#3878]
### Describe the bug

When navigating the page with the outline, the outline marker does not move to the correct item when the target header is close to the end of the page but not the last item.

### Reproduction

Visit https://vitepress.dev/reference/runtime-api and try to click on "$frontmatter" in the left-side outline.

### Expected behavior

The outline marker moves next to "$frontmatter" instead of "$params".

### System Info

```Text
A browser with window height > 1000px
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zqianem** [comment]
Possibly a duplicate of #3449

**Comment by bluwy** [comment]
It looks like this has been fixed in the latest version. (Not sure which commit)

**Comment by zqianem** [comment]
Hmm, I'm still seeing the issue:
<img width="183" height="78" alt="image" src="https://github.com/user-attachments/assets/0f7f7bcb-72c7-4bd8-82e4-9c523aec4558" />
(Firefox on Linux)

**Comment by bluwy** [comment]
Maybe it's some sort of browser-specific issue 🤔 I prefer if we could figure out the offset calculation issue rather than doing a one-off highlight-on-click fix like in the linked PR though.

**Comment by brc-dd** [comment]
It's reproducible, but I don't think offset would work in this case because both the `$frontmatter` and `$params` section are small and the document reaches end before `$frontmatter` can reach the top:

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/c57afd33-a5f5-4237-bba9-22b97c5f68c7" />

**Comment by zqianem** [comment]
Thanks for getting this fixed! ❤️
