### ISSUE TITLE
Issues with peer dependencies

### ISSUE THREAD

**Issue by lampewebdev** [vuejs/vitepress#472]
### Describe the bug

vitepress has missing peer dependencies

```
➜ pnpm up
Packages: +4 -4
++++----
Progress: resolved 777, reused 759, downloaded 2, added 4, done

devDependencies:
- @types/node 16.11.12
+ @types/node 16.11.13
- vitepress 0.20.6
+ vitepress 0.20.9

 WARN  Issues with peer dependencies found
.
└─┬ vitepress
  └─┬ @docsearch/js
    └─┬ @docsearch/react
      ├── ✕ missing peer @types/react@">= 16.8.0 < 18.0.0"
      ├── ✕ missing peer react@">= 16.8.0 < 18.0.0"
      ├── ✕ missing peer react-dom@">= 16.8.0 < 18.0.0"
      └─┬ @algolia/autocomplete-preset-algolia
        └── ✕ missing peer @algolia/client-search@^4.9.1
Peer dependencies that should be installed:
  @algolia/client-search@^4.9.1      react-dom@">= 16.8.0 < 18.0.0"     
  @types/react@">= 16.8.0 < 18.0.0"  react@">= 16.8.0 < 18.0.0" 
```

### Reproduction

`pnpm up` or `pnpm i`

### Expected behavior

Have no missing peer dependencies

### System Info

```shell
System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 2.74 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/Library/pnpm/node
    Yarn: 1.22.17 - ~/Library/pnpm/yarn
    npm: 8.1.2 - ~/Library/pnpm/npm
    Watchman: 2021.12.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.55
    Chrome Canary: 99.0.4766.0
    Firefox: 95.0
    Firefox Developer Edition: 96.0
    Firefox Nightly: 97.0a1
    Safari: 15.1
  npmPackages:
    vitepress: ^0.20.9 => 0.20.9
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Kiyozz** [comment]
I had this problem today, and solved it by removing all the node_modules from all sub-package and including the root node_modules.

After removing all node_modules, I just `pnpm i` and problem solved.

Hope it helps.

**Comment by lampewebdev** [comment]
@Kiyozz 
I'm still getting the error after running:
```
pnpm store prune
rm -rf ~/.pnpm-state ~/.pnpm-store 
pnpm prune
rm pnpm-lock.yaml
rm -rf node_modules
pnpm up
```

**Comment by Kiyozz** [comment]
Are you using pnpm workspace? Because the problem comes from workspace's packages node_modules

**Comment by lampewebdev** [comment]
@Kiyozz nope just a project

**Comment by brc-dd** [comment]
Same with Yarn PnP:

```txt
➜ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @docsearch/js@npm:3.0.0-alpha.42 doesn't provide @types/react (pa5c26), requested by @docsearch/react
➤ YN0002: │ @docsearch/js@npm:3.0.0-alpha.42 doesn't provide react (pcd160), requested by @docsearch/react
➤ YN0002: │ @docsearch/js@npm:3.0.0-alpha.42 doesn't provide react-dom (pa59c2), requested by @docsearch/react
➤ YN0002: │ @docsearch/react@npm:3.0.0-alpha.42 [280cb] doesn't provide @algolia/client-search (p52977), requested by @algolia/autocomplete-preset-algolia
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 219ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 3s 291ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 0s 385ms
➤ YN0000: Done with warnings in 4s 68ms
```

But this needs to be tracked by `@docsearch/js` and `@docsearch/react` instead. `@docsearch/js` is using `@docsearch/react` but with `preact` instead. `@docsearch/react` probably needs to put `@types/react`, etc. under `optionalDependencies`. Currently, it is safe to ignore those warnings. They don't effect the functionality of VitePress.

Create an issue at https://github.com/algolia/docsearch and reference this comment there.

**Comment by kiaking** [comment]
Currently VitePress package.json has:

```js
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "@algolia/client-search",
        "react",
        "react-dom",
        "@types/react"
      ]
    }
  }
```

But it's not stopping the warning for users side. I have no idea how to stop this 🤔

**Comment by lampewebdev** [comment]
with pnpm 7.X in the package.json this works for me but only with `pnpm`.
```json
    "pnpm": {
        "peerDependencyRules": {
            "ignoreMissing": [
                "@algolia/client-search",
                "react",
                "react-dom",
                "@types/react"
            ]
        }
    }
```

**Comment by kiaking** [comment]
Yes, but the developer who uses VitePress has to define that, and it's not that ideal 😓

It would be awesome if somehow we could configure VitePress's package.json or something and dodge the issue.

**Comment by Zelig880** [comment]
Hi guys, I really think we should add a small note on the "Getting Started" section of the documentation about this because this is probably stopping a lot of people from getting started with Vitepress!

**Comment by He110te4m** [comment]
> 

try to use this:

```
// package.json
{
  "peerDependenciesMeta": {
    "@type/react": {
      "optional": true
    }
  },
}
```

**Comment by brc-dd** [comment]
@He110te4m It won't work. That needs to be there in `@docsearch/react`'s package.json.

**Comment by kasvith** [comment]
Also encountered this problem. It worked fine with NPM though.
I'll switch to PNPM when this resolves

**Comment by xiaoxian521** [comment]
You can add something like the following to your project's package.json file, [ignoreMissing](https://pnpm.io/package_json#pnpmpeerdependencyrulesignoremissing)
```
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "react",
        "react-dom",
        "@types/react",
        "@algolia/client-search"
      ]
    }
  }
```

**Comment by benmccann** [comment]
Here's the upstream issue: https://github.com/algolia/docsearch/issues/1272

**Comment by chenweigh** [comment]
`pnpm add vitepress`

### problem
```
 WARN  Issues with peer dependencies found
site
└─┬ vitepress 1.0.0-alpha.64
  └─┬ @docsearch/js 3.3.3
    └─┬ @docsearch/react 3.3.3
      └─┬ @algolia/autocomplete-preset-algolia 1.7.4
        └── ✕ missing peer @algolia/client-search@">= 4.9.1 < 6"
Peer dependencies that should be installed:
  @algolia/client-search@">= 4.9.1 < 6"  

Done in 4.3s
```
How to fix.

**Comment by chenweigh** [comment]
> Issue with peer dependencies of `@docsearch/react` algolia/docsearch#1272

`pnpm add  @algolia/client-search` fixed.

**Comment by brc-dd** [comment]
`pnpm` v8 has `auto-install-peers=true` enabled by default, so it won't give any warnings/error for new users.

**Comment by dylantientcheu** [comment]
Hey I'm from Algolia and working on DocSearch, 

we are really sorry for this happening, is there anything we could do upstream to stop this?

These 2 dependencies are critical to DocSearch and we really cannot do without.

**Comment by brc-dd** [comment]
> is there anything we could do upstream to stop this?

@dylantientcheu Simplest fix would be to just add `@algolia/client-search` as a regular dependency of `@docsearch/react`.

Better fix would be to remove `@algolia/autocomplete-preset-algolia` from dependencies of `@docsearch/react`. AFAICT it isn't used by anything.

It is used by `@docsearch/react > @algolia/autocomplete-core`[^1], but there you have marked it as dev dependency[^2] instead of regular or peer dependency. So, it is bundled in `@algolia/autocomplete-core`[^3].

After removing from `@docsearch/react`, you can make `@algolia/autocomplete-preset-algolia` a regular dependency of `@algolia/autocomplete-core`. It will make the graph like this:

<img width="1600" height="252" alt="Image" src="https://github.com/user-attachments/assets/2c09f6c6-d955-4d90-b612-58ce7dd1e313" />

[^1]: https://github.com/algolia/autocomplete/blob/de8a1955e67b8df9a7f29f8114e3c579de86bab1/packages/autocomplete-core/src/resolve.ts#L6
[^2]: https://github.com/algolia/autocomplete/blob/de8a1955e67b8df9a7f29f8114e3c579de86bab1/packages/autocomplete-core/package.json#L38
[^3]: https://cdn.jsdelivr.net/npm/@algolia/autocomplete-core@1.17.9/dist/esm/resolve.js

**Comment by brc-dd** [comment]
Better fix would be to remove `@algolia/autocomplete-preset-algolia` from dependencies of `@docsearch/react`. AFAICT it isn't used by anything. It is used by `@docsearch/react > @algolia/autocomplete-core`, but there you have marked it as devDependency instead of regular or peer dependency. So, it is bundled in `@algolia/autocomplete-core`.

**Comment by dylantientcheu** [comment]
fixed in: https://github.com/algolia/docsearch/pull/2667/commits/3700bb86406ef155c8ffa2086f754ea41c697683

i will discuss with the autocomplete team on making `@algolia/autocomplete-preset-algolia` a regular dep

**Comment by brc-dd** [comment]
Hmm, not entirely fixed.

```
.
└─┬ @docsearch/js 4.0.0-beta.2
  └─┬ @docsearch/react 4.0.0-beta.2
    ├── ✕ missing peer search-insights@">= 1 < 3"
    ├── ✕ missing peer react@">= 16.8.0 < 20.0.0"
    ├─┬ @algolia/autocomplete-core 1.19.2
    │ └─┬ @algolia/autocomplete-plugin-algolia-insights 1.19.2
    │   └── ✕ missing peer search-insights@">= 1 < 3"
    └─┬ @ai-sdk/react 1.2.12
      ├── ✕ missing peer react@"^18 || ^19 || ^19.0.0-rc"
      └─┬ swr 2.3.4
        ├── ✕ missing peer react@"^16.11.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"
        └─┬ use-sync-external-store 1.5.0
          └── ✕ missing peer react@"^16.8.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"
```

The `@ai-sdk/react` chain is bit unfixable without bundling it.

The search-insights thing you can fix. I think it should've been a regular dependency at `@algolia/autocomplete-core` instead of being a peer dependency at `@docsearch/react`.

**Comment by brc-dd** [comment]
Ah wait a second. `@docsearch/js` ships bundled code. Why is `@docsearch/react` in dependencies then? It can be made a dev dependency. Similar reasoning as https://github.com/algolia/docsearch/pull/2566.

If you move it to devDependencies, then it will remove warnings while using vitepress or other frameworks using `@docsearch/js`.

The search-insight fix I mentioned above is still needed if you want to fix peer dependencies issues for people and frameworks using `@docsearch/react`. Also, then you don't need to do anything about `@ai-sdk/react`. People using `@docsearch/react` will have react installed.

Another benefit will be 93% smaller install size for `@docsearch/js` and 32% smaller install size for vitepress:

<img width="1091" height="408" alt="Image" src="https://github.com/user-attachments/assets/097f8371-a2e1-4bf9-850f-7a54ad5facfd" />
